name: CI

on: [push]

jobs:
  build-gcc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the example
      run: mkdir -p build-gcc && cd build-gcc && cmake .. -DRP_ENABLE_DOWNLOADING=ON
