name: CI-all-platforms

on: [push]

jobs:

  build-gcc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install opengl
      run: sudo apt update && sudo apt install -y libgtk2.0-dev libgl1-mesa-dev libglu1-mesa-dev ninja-build
    - name: Build the example
      run: mkdir -p build-gcc && cd build-gcc && cmake .. -DRP_ENABLE_DOWNLOADING=ON
    - name: Build all packages
      run: mkdir -p build-all-gcc && cd build-all-gcc && cmake ../deps -GNinja -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release && cmake --build .

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the example
      run: mkdir -p build-mac && cd build-mac && cmake .. -DRP_ENABLE_DOWNLOADING=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
    - name: Build all packages
      run: |
        export PATH=$(brew --prefix gettext)/bin:$PATH
        msgfmt --version
        mkdir -p build-all-mac 
        cd build-all-mac 
        cmake ../deps -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release 
        cmake --build . -- -j

  build-msvc:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the example
      run: |
        mkdir build-win 
        cd build-win 
        cmake .. -DRP_ENABLE_DOWNLOADING=ON
    - name: Build all packages
      run: |
        mkdir build-all-win
        cd build-all-win
        cmake ../deps -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Release -- /m
        cmake --build . --config Debug -- /m
    - uses: actions/upload-artifact@v1
      with:
        name: windows-static-64bit
        path: build-all-win/destdir/usr/local
